name: Theme feature request
description: Suggestions to improve themes and their available options
title: "Theme by Author - My Request (example text)"
labels: [enhancement, help welcome]
body:
- type: checkboxes
  attributes:
    label: Before posting
    description: Please read and acknowledge these pointers.
    options:
    - label: I understand that most themes in this project are not written by Valerio Lyndon and that this request may be closed if the theme is not maintained by Valerio Lyndon or the request is not able to be fulfilled.
      required: true
- type: input
  attributes:
    label: What theme does this request relate to?
    description: Please provide the name and author of the theme as it appears in the Customiser.
    placeholder: e.x "Dashboard by 5cm" or "ephemeral by nymphiae"
  validations:
    required: true
- type: textarea
  attributes:
    label: What is your desired change or feature?
    description: A concise description of the missing feature or option that you want. Screenshots can help to describe.
    placeholder: e.x "dark mode" or "support for the tag column"
  validations:
    required: true
- type: textarea
  attributes:
    label: Do you have a code prototype/example? (optional)
    description: This can greatly help in adding your feature.
    placeholder: Place your CSS or a link to CSS here.
    render: shell
  validations:
    required: false
